config/routes.rb
BabyCloudApp::Application.routes.draw do
  
  get "comments/create"
  resources :posts 
  get '/years/:year' => "posts#months", :as => "year_posts"
  get '/years/:year/:month' => "posts#single_month", :as => "month_posts"
  get '/no_year' => "posts#no_year", :as => "no_year"

  devise_for :admins

  resources :comments

  devise_for :users
  resources :users, only: [:show]
  get '/explore' => "posts#grid"

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	acts_as_likeable
	validates_length_of :content, allow_blank: false
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
  has_many :comments
  acts_as_likeable

	has_attached_file :image,
     :styles => {
      :original => ['1920x1680>', :jpg, :convert_options => "-auto-orient"],
      :small    => ['100x100#',   :jpg, :convert_options => "-auto-orient"],
      :medium   => ['250x250',    :jpg, :convert_options => "-auto-orient"],
      :large    => ['600x600>',   :jpg, :convert_options => "-auto-orient"]
    }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
		
    before_post_process :load_exif

  	validates_attachment_presence :image

  	def load_exif
  		exif = EXIFR::JPEG.new(image.queued_for_write[:original].path)

  		# Return if exif.nil? or not exif.exif?
  		self.date = exif.date_time.to_date
  		# self.latitude = exif.gps.latitude
  		# self.longitude = exif.gps.longitude
  	rescue
  		false
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :posts

  has_attached_file :avatar, :styles => { 
  	:medium => "300x300>", :thumb => "50x50>" }

  # has_attached_file :picture,
  #    :styles => {
  #     :original => ['1920x1680>', :jpg, :convert_options => "-auto-orient"],
  #     :small    => ['100x100#',   :jpg, :convert_options => "-auto-orient"],
  #     :medium   => ['250x250',    :jpg, :convert_options => "-auto-orient"],
  #     :large    => ['600x600>',   :jpg, :convert_options => "-auto-orient"]
  #   }

  validates_attachment    :avatar,
                          # presence: true,
                          content_type: { content_type: /\Aimage\/.*\Z/ },
                          size: { less_than: 2.megabyte }

  acts_as_follower
  acts_as_followable
  acts_as_liker
  acts_as_mentionable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :avatar) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:comment][:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to @post
  end

  private 

  def comment_params
  	params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    post_ids = current_user.posts.select("MAX(id)").group("date_part('year', date(date))")
    @user_posts = Post.where(:id => post_ids).order("date DESC")
  end

  def months
    post_ids = current_user.posts.select("MAX(id)").group("date_part('month', date(date))").where("date_part('year', date(date)) = ?", params[:year])
    @user_posts = Post.where(:id => post_ids).order("date DESC")
  end

  def single_month
    @user_posts = current_user.posts.where("date_part('year', date(date)) = ?", params[:year]).where("date_part('month', date(date)) = ?", params[:month]).order("date DESC")
  end

  def no_year
    @user_posts = current_user.posts.where(:date => nil).order("created_at DESC")
    render 'single_month'
  end

  def grid
    @posts = Post.all.reverse
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.username = current_user.username
    if @post.save
      render json: { message: "success" }, :status => 200
    else
      #  you need to send an error header, otherwise Dropzone
      #  will not interpret the response as an error:
      render json: { error: @post.errors.full_messages.join(',')}, :status => 400
    end
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to @post, notice: 'Post was deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, only: [:show, :edit, :update]

  def index
     @user_posts = Post.all
  end

	def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end 

  def update

  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:sucess] = "Signed Up Successfully"
  		redirect_to explore_path
  	else
  		render :new
  	end
  end

  protected

  def user_params
  	params.require(:user).permit(:email, :password, :avatar)
  end

  def find_user
    @user = User.find_by(email: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Baby Cloud</a>
  </div>
  
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% else %>
        <li><%= link_to "Explore", explore_path %></li>
        <li><%= link_to "Gallery", posts_path %></li>
        <li><%= link_to "Upload", new_post_path %></li>
        <!-- <li><%#= link_to current_user.name, user_path(current_user.name.gsub(" ", "_")) %></li> -->
        <li class="round-image-50"><%= image_tag(current_user.avatar.url) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BabyCloudApp</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/navbar" %>

<%= yield %>

<script type="text/javascript">
	var s = skrollr.init();
</script>

</body>
</html>

app/views/posts/_comment_form.html.erb
<%= form_for @comment do |f| %>
	<% if @comment.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>
	  <ul>
		  <% @comment.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
	  </ul>
	</div>
	<% end %>
	<%= f.hidden_field :post_id, value: @post.id %>

	<div>
		<%= f.text_area :content %>
	</div>
	<div>
		<%= f.submit "Submit Comment", class: "btn btn-sm" %>
	</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true, class: "dropzone"}) do |f|  %>
  <div class="fallback">
    <%= f.file_field :image %><br>
    <%= f.submit "Upload" %>
  </div>
<% end %>
<br>

app/views/posts/_grid_post.html.erb
<div class="item col-md-4">
  <div class="thumbnail img-responsive">
    <%= image_tag post.image.url %>
    <div class="hover-description">        
      <h5 ><%= post.title %></h5>

      <!-- <h5><%= post.description %></h5> -->
        
      <h5><%= post.date %></h5> 
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		
		<div class="col-md-8">
			<% if @post.image_content_type %>
				<%= image_tag @post.image.url, class: "img-thumbnail"%>
			<% end %>				
		</div>

		<div class="col-md-4">
			<%= form_for @post, :html => { :multipart => true } do |f| %>
				<h2>Title</h2>
				<%= f.text_field :title, class: "form-control" %>
				
				<h2>Description</h2>
				<%= f.text_area :description, size: "30x10", class: "form-control" %>
				<br>

				<%= f.submit "Update", class: "btn btn-success" %>
			<% end %>
		</div>
		
	</div>
</div>

app/views/posts/grid.html.erb
<div class="container">
  <div id="posts" class="row">

    <% @posts.each do |post| %>        
      <%= link_to (post) do %>
      <div class="item col-md-2">
        <div class="thumbnail img-responsive">
          <%= image_tag post.image.url %>
          <div class="hover-description">
              <h5><%= post.title %></h5>
              <!-- <h5><%= post.description %></h5> -->
              <h5><%= post.date %></h5> 
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
      
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div id="posts" class="row">

		<% @user_posts.each do |post| %>			
			<%= link_to (post.date ? year_posts_path(:year => Date.parse(post.date).year) : no_year_path) do %>
        <%= render :partial => 'grid_post', :locals => { post: post } %>
			<% end %>
		<% end %>
			
	</div>
</div>

app/views/posts/months.html.erb
<div class="container">
  <div id="posts" class="row">
    <% @user_posts.each do |post| %>     
      <%= link_to month_posts_path(:year => Date.parse(post.date).year, :month => Date.parse(post.date).month) do %>
      
       <%= render :partial => 'grid_post', :locals => { post: post } %>

      <% end %>
    <% end %>  
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<%= render 'form' %> <!-- Image Upload -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Drag & Drop</h3>
        </div>
        
        <div class="panel-body">
          <li>Up to 5mb per photo can be uploaded</li>
          <li>Maximum of 50 photos per load</li>
          <li>Accepts jpeg & png</li>
        </div>
      </div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<div class="thumbnail img-responsive">
				<% if @post.image_content_type %>
					<%= image_tag @post.image.url, class: "img-responsive"%>
				<% end %>
			</div>	
		</div>

		<div class="col-md-4">
			<h3>By</h3>
			<%= link_to @post.username, @post.user %>
			<hr>

			<h3>Title</h3>
			<%= @post.title %>
			<hr>
					
			<h3>Description</h3> 
			<%= @post.description %>
			<hr>

			<h3>Date</h3>
      <%= @post.date %>
			<hr>

			<h3>Comments</h3>
      <% @post.comments.each do |comment| %>
      	<%= image_tag comment.user.avatar.url, class: "square-image-50" %>
				<%= link_to comment.user.username, comment.user %>
				<div class="comment-content">
					<%= comment.content %>
				</div>
				<div class="comment-date">
					<%= comment.created_at.to_formatted_s(:long) %>
				</div>
				<hr>
			<% end %>

			<%= render 'comment_form' %>
			<hr>

			<% if (@post.user_id == current_user.id) %>
				<%= link_to 'Edit', edit_post_path, class: "btn btn-success btn-sm"%>
				<%= link_to 'Delete', @post, {method: :delete, data: {confirm: "Are you sure you want to delete this adorable photo?"}, class: "btn btn-danger btn-sm"} %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/single_month.html.erb
<div class="container">
  <div id="posts" class="row">
    <% @user_posts.each do |post| %>
	    <%= link_to (post) do %>
	    
	      <%= render :partial => 'grid_post', :locals => { post: post } %>

	    <% end %>
    <% end %>   
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<section id="slide-1">
	<div class="slide1 home">
		<div
	    data-center="opacity: 1"
	    data-center-top="opacity: 1"
	    data--150-bottom="opacity: 0;"
	    data-anchor-target="#slide-1"
    >
    	<div class="container">
		    <div class="row">
		      <div class="col-xs-4 col-sm-4 col-md-4">
		        <h1>Share your baby photos with family and friends today!</h1>
		        <p>Join the community.</p>
		        <%= link_to "Join Baby Cloud", new_user_registration_path, class: "btn btn-info btn-lg" %>
		      </div>
		    </div>
      	<img id="cloud1" src="assets/cloudsmall.png">
	  	</div>
	  </div>
	</div>
</section>

<section id="slide-2">	
	<div class="slide2 home">
		<div
	    data-center="opacity: 1"
	    data-center-top="opacity: 1"
	    data--300-bottom="opacity: 0;"
	    data-anchor-target="#slide-2"
	  >
	  	<div class="timeline">
				<p>Organize and sort your photos</p>
				<%= link_to "Upload your first photo", new_user_registration_path, class: "btn btn-info btn-lg" %>
			</div>
	    <img id="cloud2" src="assets/cloudnew.png">
	  </div>
	</div>
</section>

<section id="slide-3">
	<div class="slide3 home">
		<div
			data-center="opacity: 1"
	    data-center-top="opacity: 0.5"
	    data-bottom="opacity: 0.7;"
		>
			<div class="connect">
				<p>Connect with other parents</p>
				<%= link_to "Start connecting", new_user_registration_path, class: "btn btn-info btn-lg" %>
			</div>
			<div class="connect1"></div>
			<div class="connect2"></div>
			<div class="connect3"></div>
		</div>
		<div 
      data-bottom-top="opacity: 0"
      data-25p-top="opacity: 0"
      data-top="opacity: 1" 
      data-anchor-target="#slide-3"
    >
	    <img id="cloud3" src="assets/cloudnew.png">
  	</div>
	</div>
</section>

app/views/users/show.html.erb
<div class="container">
  <div id="posts" class="row">

    <% @posts.each do |post| %>        
      <%= link_to (post) do %>
      <div class="item col-md-2">
        <div class="thumbnail img-responsive">
          <%= image_tag post.image.url %>
          <div class="hover-description">
              <h5><%= post.title %></h5>
              <!-- <h5><%= post.description %></h5> -->
              <h5><%= post.date %></h5> 
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
      
  </div>
</div>